version: "3"
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/split-bill-ui
    working_dir: /split-bill-ui
    command: npm install
